const Anthropic = require('@anthropic-ai/sdk');

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

const REFINE_MODEL = process.env.REFINE_MODEL || 'claude-haiku-4-5-20251001';

const GRADE_SCALE = [
  [8.5, 'A'], [7.5, 'B+'], [6.5, 'B'],
  [5.5, 'C+'], [4.5, 'C'], [3.5, 'D'], [0, 'F'],
];
function grade(score) {
  for (const [threshold, letter] of GRADE_SCALE) {
    if (score >= threshold) return letter;
  }
  return 'F';
}

/**
 * Sends the raw Python AI report + original screenshot to Claude Haiku (vision).
 * Claude filters hallucinated issues and adjusts scores based on what it
 * actually sees in the image, then returns a refined report.
 *
 * Falls back silently to the original report if Claude fails.
 */
async function refineReport(rawReport, imageBuffer, imageMimeType) {
  if (!process.env.ANTHROPIC_API_KEY) {
    console.warn('[refine] ANTHROPIC_API_KEY not set — skipping refinement');
    return withHeuristicsAlias(rawReport);
  }

  try {
    const imageBase64 = Buffer.isBuffer(imageBuffer)
      ? imageBuffer.toString('base64')
      : imageBuffer;

    const prompt = `You are reviewing an automated UX evaluation report for the attached UI screenshot.

The report was generated by an AI model that scores UIs against Nielsen's 10 heuristics using image embeddings. It often flags issues that are NOT actually visible in the screenshot — for example flagging "no close button on modal" when no modal exists, or "error messages are unclear" when there are no error messages shown.

YOUR TASKS:
1. Look at the screenshot carefully
2. For each issue, decide: is this actually visible or applicable to THIS specific UI?
3. Remove any issue that is NOT present in the image (hallucinated)
4. Keep issues that genuinely apply to what you see
5. Adjust individual heuristic scores slightly if they seem wrong for this image
6. Rewrite kept issue descriptions to be specific to what you actually observe

ORIGINAL REPORT DATA:
${JSON.stringify({ heuristic_scores: rawReport.heuristic_scores, issues: rawReport.issues }, null, 2)}

Return ONLY a valid JSON object with exactly this structure — no markdown, no explanation:
{
  "heuristic_scores": [
    { "id": "h1", "name": "...", "score": <0-10 float>, "weight": <same as original>, "issue": "...", "solution": "..." }
    ... all 10 heuristics in original order
  ],
  "issues": [
    { "heuristic_id": "...", "heuristic_name": "...", "severity": "high"|"medium"|"low", "issue": "specific to this image", "solution": "actionable fix", "source": "refined" }
    ... only issues genuinely visible in this screenshot
  ]
}`;

    const response = await client.messages.create({
      model:      REFINE_MODEL,
      max_tokens: 4096,
      system:     'You are a UX expert. Return only valid JSON, nothing else. No markdown fences.',
      messages: [
        {
          role: 'user',
          content: [
            {
              type:   'image',
              source: { type: 'base64', media_type: imageMimeType, data: imageBase64 },
            },
            { type: 'text', text: prompt },
          ],
        },
      ],
    });

    const text    = response.content[0].text.trim();
    const clean   = text.replace(/^```(?:json)?\n?/i, '').replace(/\n?```$/i, '').trim();
    const refined = JSON.parse(clean);

    const scores      = refined.heuristic_scores?.length ? refined.heuristic_scores : rawReport.heuristic_scores;
    const weighted    = scores.reduce((s, h) => s + h.score * (h.weight ?? 1), 0);
    const weightTotal = scores.reduce((s, h) => s + (h.weight ?? 1), 0);
    const overall     = Math.round((weighted / weightTotal) * 100) / 100;

    console.log(`[refine] original issues: ${rawReport.issues?.length ?? 0} → refined: ${refined.issues?.length ?? 0}`);

    return {
      ...rawReport,
      heuristic_scores: scores,
      heuristics:       scores,
      issues:           refined.issues ?? [],
      overall_score:    overall,
      grade:            grade(overall),
    };
  } catch (err) {
    console.error('[refine] Claude refinement failed, using original report:', err.message);
    return withHeuristicsAlias(rawReport);
  }
}

function withHeuristicsAlias(report) {
  return { ...report, heuristics: report.heuristic_scores || [] };
}

module.exports = { refineReport };
